version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8000:8000
    volumes:
    - ./restaurant:/app
  cli:
    build:
      context: .
      dockerfile: Dockerfile
    command: echo "Starting cli..."
    volumes:
    - ./restaurant:/app