# Generated by Django 3.0.6 on 2020-05-23 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200517_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersummary',
            name='order_ptr',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderSummary',
        ),
    ]
